<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE datasource [
        <!ELEMENT datasource (source-name, connection-url, driver-class, user-name, password)*>
        <!ELEMENT source-name (#PCDATA)>
        <!ELEMENT connection-url (#PCDATA)>
        <!ELEMENT driver-class (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT user-name (#PCDATA)>
        ]>
<datasource>
    <source-name>orcl</source-name>
    <connection-url>jdbc:oracle:thin:@localhost:1521:</connection-url>
    <driver-class>oracle.jdbc.driver.OracleDriver</driver-class>
    <user-name>sys as sysdba</user-name>
    <password>root</password>
</datasource>
